language: python
dist: xenial
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install .
script:
  - pip install coveralls
  - pip install pytest-timeout
  - coverage run -m pytest tests_common/
  - coveralls
notifications:
  slack: bayeso:FWBoHH9TMqjKUJWkZxCaTNVE
