language: python
matrix:
    include:
        - "2.7"
        dist: trusty
        sudo: false
        - "3.5"
        dist: trusty
        sudo: false
        - "3.6"
        dist: trusty
        sudo: false
        - "3.7"
        dist: xenial
        sudo: true
install:
  - pip install .
script:
  - pytest
after_success:
  - pip install coveralls
  - coverage run -m pytest
  - coveralls
notifications:
  slack: bayeso:FWBoHH9TMqjKUJWkZxCaTNVE
