language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install .
script:
  - pytest
after_success:
  - pip install coveralls
  - coverage run -m pytest
  - coveralls
notifications:
  slack: bayeso:FWBoHH9TMqjKUJWkZxCaTNVE
